version: '3'
services:
  webapi:
    build: .
    #build:
    #  context: .
    #  #context: ./myAPI
    #  dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8081:443
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
     - 5432:5432

volumes:
  db-data:
